// <auto-generated/>
#pragma warning disable CS0618
using InfiniLore.KiotaApiClient.Api.Item.Lorescopes.Item;
using InfiniLore.KiotaApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace InfiniLore.KiotaApiClient.Api.Item.Lorescopes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\{userId}\lore-scopes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LorescopesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the InfiniLore.KiotaApiClient.api.item.Lorescopes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.Item.WithLorescopeItemRequestBuilder"/></returns>
        public global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.Item.WithLorescopeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("LorescopeId", position);
                return new global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.Item.WithLorescopeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.LorescopesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LorescopesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/{userId}/lore-scopes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.LorescopesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LorescopesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/{userId}/lore-scopes", rawUrl)
        {
        }
        /// <returns>A List&lt;global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsLorescopeResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsLorescopeResponse>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsLorescopeResponse>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsLorescopeResponse>(requestInfo, global::InfiniLore.KiotaApiClient.Models.InfiniLoreServerAPIModelsLorescopeResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.LorescopesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.LorescopesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::InfiniLore.KiotaApiClient.Api.Item.Lorescopes.LorescopesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
