name: User Story
description: Template for creating user stories
title: 'UserStory | '
assignees:
  - AndreasSas
labels:
  - user story
  - enhancement
projects:
  - InfiniLore/1
body:
  - type: markdown
    attributes:
      value: >+
        ### InfiniLore : User Story

        User stories provide a clear, simple way to describe the features we're working on and their scope. Just follow the example and you'll be fine.

        ---

  - type: textarea
    id: who-what-why
    attributes:
      label: The Who - What - Why
      description: >-
        Who is this feature for? What is the feature? Why is it important?
      placeholder: 'As a ...  I want to ... So that ...'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: >-
        Any other info or links about this feature (Optional)
      placeholder: ex. Screenshots, diagrams, or other references
  - type: markdown
    attributes:
      value: |-
        ---
        # Acceptance Criteria

         Define what should be true for the feature to be considered complete.
  - type: textarea
    id: acceptance-criteria-user
    attributes:
      label: User-Side Criteria
      description: >-
        What should the user be able to do once this feature is implemented? (Optional)
      placeholder: >-
        ex. When I create a new asset, I should be able to link it with existing elements
  - type: textarea
    id: acceptance-criteria-dev
    attributes:
      label: Dev-Side Criteria
      description: >-
        Specific technical requirements for developers (if applicable)
  - type: markdown
    attributes:
      value: |-
        <br>

        ---
        <br>
  - type: checkboxes
    id: ducky
    attributes:
      label: Ducky Acknowledgment
      description: Acknowledge that the developer may decide to delay or re-prioritize this issue.
      options:
        - label: >-
            I accept that this issue might be delayed or deprioritized.
          required: true
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms Creator](https://issue-forms-creator.netlify.app)
