name: "Run TODO to Issue"
on:
  push:
    branches:
      - core-development
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          PROJECT: "organization/InfiniLore/InfiniLore"
          PROJECTS_SECRET: "${{ secrets.PROJECTS_SECRET }}"
          ISSUE_TEMPLATE: |
            ### 📝 Todo Task
            **Description:**  
            {{ title }}

            **Details:**  
            {{ body }}

            **File:**  
            {{ url }}

            **Code Snippet:**
            ```  
            {{ snippet }}
            ```

          IDENTIFIERS: '[{"name": "TODO", "labels": ["todo"]}]'
          CLOSE_ISSUES: "true"
