name: "Run TODO to Issue"
on:
  push:
    branches:
      - core-development
env:
  PROJECT: "organization/InfiniLore/InfiniLore"
  PROJECTS_SECRET: "${{ secrets.PROJECTS_SECRET }}"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
